---
- name: G2P install
  hosts: all
  become: yes

  tasks:
    - name: Update and upgrade system
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400


# MONGODB
    - name: MongoDB | Import public key
      apt_key:
        url: 'https://www.mongodb.org/static/pgp/server-6.0.asc'
        state: present

    - name: MongoDB | Add repository
      apt_repository:
        filename: '/etc/apt/sources.list.d/mongodb-org-6.0.list'
        repo: 'deb https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse'
        state: present
        update_cache: yes

    - name: MongoDB | Install
      become: true
      apt:
        name: mongodb-org
        state: present
        update_cache: yes


# JENKINS
    - name: Jenkins | Add APT Key
      ansible.builtin.shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
        /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      tags:
        - jenkins

    - name: Jenkins | Write repository entry
      ansible.builtin.shell: |
        echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
        https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
        /etc/apt/sources.list.d/jenkins.list > /dev/null
      tags:
        - jenkins


# JAVA ORACLE
#    - name: Oracle Java | Add Repository
#      become: yes
#      apt_repository:
#        repo: "ppa:linuxuprising/java"
#      tags:
#        - oracle-java
#    
#    - name: Oracle Java | Accept License
#      become: yes
#      debconf:
#        name: "oracle-java17-installer"
#        question: "shared/accepted-oracle-license-v1-1"
#        value: "true"
#        vtype: "select"
#      tags:
#        - oracle-java
#    
#    - name: Oracle Java | Install Java 8
#      become: yes
#      apt:
#        name: "{{item}}"
#        state: latest
#      with_items:
#        - oracle-java17-installer
#        - oracle-java17-set-default
#      tags:
#        - oracle-java


# Install Packages
    - name: APT | Install dependence packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - git
        - vim
        - openjdk-11-jre
        - openjdk-11-jdk
        - build-essential
        - unixodbc
        - unixodbc-dev
        - odbcinst
        - libbz2-dev
        - libffi-dev
        - liblzma-dev
        - libncursesw5-dev
        - libreadline-dev
        - libsqlite3-dev
        - libssl-dev
        - libxml2-dev
        - libxmlsec1-dev
        - zlib1g-dev
        - python-is-python3
        - jenkins
        - unzip


    - name: BASH | Setting local bin folder for non root user
      become_user: "{{ lookup('env', 'USER') }}"
      lineinfile:
        line: "{{ item }}"
        path: ~/.bashrc
      with_items:
        - "# set local/bin folder"
        - "export PATH=$PATH:$HOME/.local/bin"


# ASDF-VM
    - name: ASDF-VM
      become_user: "{{ lookup('env', 'USER') }}"
      git:
        repo: "https://github.com/asdf-vm/asdf.git"
        dest: ~/.asdf
        version: v0.11.1

    - name: ASDF-VM | add bashrc
      become_user: "{{ lookup('env', 'USER') }}"
      lineinfile:
        line: "{{ item }}"
        path: ~/.bashrc
      with_items:
        - "# asdf-vm"
        - ". $HOME/.asdf/asdf.sh"
        - ". $HOME/.asdf/completions/asdf.bash"

    - name: ASDF-VM | plugins install
      become_user: "{{ lookup('env', 'USER') }}"
      shell: "$HOME/.asdf/bin/asdf plugin-add {{ item }}"
      ignore_errors: yes
      with_items:
        - python

    - name: ASDF-VM | Install Python 3.8.x
      become_user: "{{ lookup('env', 'USER') }}"
      shell: "$HOME/.asdf/bin/asdf install python 3.8.16"


# VARIABLES
    - name: Include variables for git commands
      ansible.builtin.include_vars:
        file: variables.yaml
        name: var
      tags:
        - g2p

# G2P
# https://hubsd@dev.azure.com/hubsd/DATA%20PLATAFORMA/_git/g2p
    - name: Download G2P
      become_user: "{{ lookup('env', 'USER') }}"
      git:
        repo: "https://{{ var.git_user | urlencode }}:{{ var.git_pass | urlencode }}@dev.azure.com/hubsd/DATA%20PLATAFORMA/_git/g2p"
        dest: ~/apps/G2P
        force: yes
      tags:
        - g2p


# git@ssh.dev.azure.com:v3/hubsd/DATA%20PLATAFORMA/g2p-luigi
# https://hubsd@dev.azure.com/hubsd/DATA%20PLATAFORMA/_git/g2p-luigi
    - name: Download G2P
      become_user: "{{ lookup('env', 'USER') }}"
      git:
        repo: "https://{{ var.git_user | urlencode }}:{{ var.git_pass | urlencode }}@dev.azure.com/hubsd/DATA%20PLATAFORMA/_git/g2p-luigi"
        dest: ~/apps/G2P-LUIGI
        force: yes
      tags:
        - g2p
        
    - name: Create some directories
      become_user: "{{ lookup('env', 'USER') }}"
      file:
        path: "~/{{ item }}"
        state: directory
      with_items:
        - apps
        - apps/metabase
        - apps/files
      tags:
        - metabase


# G2P
# git@ssh.dev.azure.com:v3/hubsd/DATA%20PLATAFORMA/g2p
#     - name: Download G2P
#       become_user: "{{ lookup('env', 'USER') }}"
#       git:
#         repo: "git@ssh.dev.azure.com:v3/hubsd/DATA%20PLATAFORMA/g2p"
#         dest: ~/G2P
#         ikey_file: ~/senai-0023793
#         accept_hostkey: yes
#         force: yes
# 
# 
# # git@ssh.dev.azure.com:v3/hubsd/DATA%20PLATAFORMA/g2p-luigi
#     - name: Download G2P
#       become_user: "{{ lookup('env', 'USER') }}"
#       git:
#         repo: "git@ssh.dev.azure.com:v3/hubsd/DATA%20PLATAFORMA/g2p-luigi"
#         dest: ~/G2P-LUIGI
#         key_file: ~/senai-0023793
#         accept_hostkey: yes
#         force: yes
#         
#     - name: Create some directories
#       become_user: "{{ lookup('env', 'USER') }}"
#       file:
#         path: "~/{{ item }}"
#         state: directory
#       with_items:
#         - .apps
#         - .apps/metabase
#         - .apps/files
#       tags:
#         - metabase


# METABASE
    - name: Download Metabase
      become_user: "{{ lookup('env', 'USER') }}"
      ansible.builtin.get_url:
        url: https://downloads.metabase.com/v0.45.2.1/metabase.jar
        dest: ~/apps/metabase/metabase.jar
      tags:
        - metabase


# PENTAHO
    - name: Pentaho | Download
      become_user: "{{ lookup('env', 'USER') }}"
      ansible.builtin.get_url:
        url: https://sourceforge.net/projects/pentaho/files/Pentaho-9.3/client-tools/pdi-ce-9.3.0.0-428.zip/download
        dest: ~/apps/files/pdi-ce-9.3.0.0-428.zip
        checksum: sha256:5c7a453ec448d4b8a568e445b119bcf4f0f41517b42e3626bc437f882c9f46c1
      tags:
        - pentaho

    - name: Pentaho | Extract file
      become_user: "{{ lookup('env', 'USER') }}"
      ansible.builtin.unarchive:
        src: ~/apps/files/pdi-ce-9.3.0.0-428.zip
        dest: ~/apps
      tags:
        - pentaho


# Pentaho mssql-jdbc drivers
    - name: Pentaho | Download mssql-jdbc drivers
      become_user: "{{ lookup('env', 'USER') }}"
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: ~/apps/files
      with_items:
        - https://github.com/microsoft/mssql-jdbc/releases/download/v9.4.1/mssql-jdbc-9.4.1.jre8.jar
        - https://github.com/microsoft/mssql-jdbc/releases/download/v11.2.1/mssql-jdbc-11.2.1.jre8.jar
      tags:
        - pentaho

    - name: Pentaho | Copy mssql-jdbc drivers to program path
      become_user: "{{ lookup('env', 'USER') }}"
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: ~/apps/data-integration/lib
      with_items:
        - ~/apps/files/mssql-jdbc-9.4.1.jre8.jar
        - ~/apps/files/mssql-jdbc-11.2.1.jre8.jar 
      tags:
        - pentaho

    - name: Pentaho | Add Repository libwebkitgtk-1.0-0
      become: yes
      apt_repository:
        repo: "deb [trusted=yes] http://br.archive.ubuntu.com/ubuntu bionic main universe"
      tags:
        - pentaho

    - name: APT | Install libwebkitgtk-1.0-0
      become: yes
      apt:
        name: "libwebkitgtk-1.0-0"
        state: present
        update_cache: yes
      tags:
        - pentaho

# DBEAVER
    - name: Dbeaver | Download
      become_user: "{{ lookup('env', 'USER') }}"
      ansible.builtin.get_url:
        url: https://dbeaver.io/files/dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
        dest: ~/apps/files/dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
        checksum: sha256:ab1c041d8f6962b01beb7ff9e8c7299c72f28e87b606fe319e65557650aab098
      tags:
        - dbeaver

    - name: Dbeaver | Extract file
      become_user: "{{ lookup('env', 'USER') }}"
      ansible.builtin.unarchive:
        src: ~/apps/files/dbeaver-ce-latest-linux.gtk.x86_64.tar.gz
        dest: ~/apps
      tags:
        - dbeaver


# https://downloads.mongodb.com/compass/mongodb-compass_1.35.0_amd64.deb
    - name: MongoDB | Download MongoDB Compass
      become_user: "{{ lookup('env', 'USER') }}"
      ansible.builtin.get_url:
        url: https://downloads.mongodb.com/compass/mongodb-compass_1.35.0_amd64.deb
        dest: ~/apps/files/mongodb-compass_1.35.0_amd64.deb
        checksum: sha256:5d29e1bf7f795f41ba9fb1b7310c6fa1204ead2ddc855e9f2e39b15d16922544
      tags:
        - compass

    - name: APT | Install MongoDB Compass
      become: yes
      ansible.builtin.apt:
        deb: "/home/{{ lookup('env', 'USER') }}/apps/files/mongodb-compass_1.35.0_amd64.deb"
        update_cache: yes
      tags:
        - compass
